// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: api/v2/collo.proto

package apiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ColloRateWebStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword      string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	From         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Until        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
	ForcusNodeId uint32                 `protobuf:"varint,4,opt,name=forcus_node_id,json=forcusNodeId,proto3" json:"forcus_node_id,omitempty"`
}

func (x *ColloRateWebStreamRequest) Reset() {
	*x = ColloRateWebStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v2_collo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColloRateWebStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColloRateWebStreamRequest) ProtoMessage() {}

func (x *ColloRateWebStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_collo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColloRateWebStreamRequest.ProtoReflect.Descriptor instead.
func (*ColloRateWebStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_v2_collo_proto_rawDescGZIP(), []int{0}
}

func (x *ColloRateWebStreamRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ColloRateWebStreamRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ColloRateWebStreamRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *ColloRateWebStreamRequest) GetForcusNodeId() uint32 {
	if x != nil {
		return x.ForcusNodeId
	}
	return 0
}

type ColloRateWebStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*RateNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges []*RateEdge `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	Dones uint32      `protobuf:"varint,3,opt,name=dones,proto3" json:"dones,omitempty"`
	Needs uint32      `protobuf:"varint,4,opt,name=needs,proto3" json:"needs,omitempty"`
}

func (x *ColloRateWebStreamResponse) Reset() {
	*x = ColloRateWebStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v2_collo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColloRateWebStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColloRateWebStreamResponse) ProtoMessage() {}

func (x *ColloRateWebStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_collo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColloRateWebStreamResponse.ProtoReflect.Descriptor instead.
func (*ColloRateWebStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_v2_collo_proto_rawDescGZIP(), []int{1}
}

func (x *ColloRateWebStreamResponse) GetNodes() []*RateNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ColloRateWebStreamResponse) GetEdges() []*RateEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *ColloRateWebStreamResponse) GetDones() uint32 {
	if x != nil {
		return x.Dones
	}
	return 0
}

func (x *ColloRateWebStreamResponse) GetNeeds() uint32 {
	if x != nil {
		return x.Needs
	}
	return 0
}

type RateNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId uint32  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Word   string  `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	Rate   float32 `protobuf:"fixed32,3,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *RateNode) Reset() {
	*x = RateNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v2_collo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateNode) ProtoMessage() {}

func (x *RateNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_collo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateNode.ProtoReflect.Descriptor instead.
func (*RateNode) Descriptor() ([]byte, []int) {
	return file_api_v2_collo_proto_rawDescGZIP(), []int{2}
}

func (x *RateNode) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RateNode) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *RateNode) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type RateEdge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EdgeId  uint32  `protobuf:"varint,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	NodeId1 uint32  `protobuf:"varint,2,opt,name=node_id1,json=nodeId1,proto3" json:"node_id1,omitempty"`
	NodeId2 uint32  `protobuf:"varint,3,opt,name=node_id2,json=nodeId2,proto3" json:"node_id2,omitempty"`
	Rate    float32 `protobuf:"fixed32,4,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *RateEdge) Reset() {
	*x = RateEdge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v2_collo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateEdge) ProtoMessage() {}

func (x *RateEdge) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_collo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateEdge.ProtoReflect.Descriptor instead.
func (*RateEdge) Descriptor() ([]byte, []int) {
	return file_api_v2_collo_proto_rawDescGZIP(), []int{3}
}

func (x *RateEdge) GetEdgeId() uint32 {
	if x != nil {
		return x.EdgeId
	}
	return 0
}

func (x *RateEdge) GetNodeId1() uint32 {
	if x != nil {
		return x.NodeId1
	}
	return 0
}

func (x *RateEdge) GetNodeId2() uint32 {
	if x != nil {
		return x.NodeId2
	}
	return 0
}

func (x *RateEdge) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

var File_api_v2_collo_proto protoreflect.FileDescriptor

var file_api_v2_collo_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x32, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbd, 0x01,
	0x0a, 0x19, 0x43, 0x6f, 0x6c, 0x6c, 0x6f, 0x52, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x30, 0x0a, 0x05, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x05, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x6f, 0x72, 0x63, 0x75,
	0x73, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0c, 0x66, 0x6f, 0x72, 0x63, 0x75, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x98, 0x01,
	0x0a, 0x1a, 0x43, 0x6f, 0x6c, 0x6c, 0x6f, 0x52, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x61, 0x74,
	0x65, 0x45, 0x64, 0x67, 0x65, 0x52, 0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x64, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x64, 0x6f, 0x6e,
	0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x65, 0x65, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x6e, 0x65, 0x65, 0x64, 0x73, 0x22, 0x4b, 0x0a, 0x08, 0x52, 0x61, 0x74, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x6d, 0x0a, 0x08, 0x52, 0x61, 0x74, 0x65, 0x45, 0x64, 0x67,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x65, 0x64, 0x67, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x69, 0x64, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x31, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64,
	0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x32,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04,
	0x72, 0x61, 0x74, 0x65, 0x32, 0x74, 0x0a, 0x13, 0x43, 0x6f, 0x6c, 0x6c, 0x6f, 0x52, 0x61, 0x74,
	0x65, 0x57, 0x65, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x12, 0x43,
	0x6f, 0x6c, 0x6c, 0x6f, 0x52, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x6f,
	0x52, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x6f,
	0x6c, 0x6c, 0x6f, 0x52, 0x61, 0x74, 0x65, 0x57, 0x65, 0x62, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x2a, 0x5a, 0x28, 0x79, 0x79,
	0x79, 0x6f, 0x69, 0x63, 0x68, 0x69, 0x2f, 0x43, 0x6f, 0x6c, 0x6c, 0x6f, 0x2d, 0x41, 0x50, 0x49,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32,
	0x3b, 0x61, 0x70, 0x69, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v2_collo_proto_rawDescOnce sync.Once
	file_api_v2_collo_proto_rawDescData = file_api_v2_collo_proto_rawDesc
)

func file_api_v2_collo_proto_rawDescGZIP() []byte {
	file_api_v2_collo_proto_rawDescOnce.Do(func() {
		file_api_v2_collo_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v2_collo_proto_rawDescData)
	})
	return file_api_v2_collo_proto_rawDescData
}

var file_api_v2_collo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v2_collo_proto_goTypes = []interface{}{
	(*ColloRateWebStreamRequest)(nil),  // 0: api.v2.ColloRateWebStreamRequest
	(*ColloRateWebStreamResponse)(nil), // 1: api.v2.ColloRateWebStreamResponse
	(*RateNode)(nil),                   // 2: api.v2.RateNode
	(*RateEdge)(nil),                   // 3: api.v2.RateEdge
	(*timestamppb.Timestamp)(nil),      // 4: google.protobuf.Timestamp
}
var file_api_v2_collo_proto_depIdxs = []int32{
	4, // 0: api.v2.ColloRateWebStreamRequest.from:type_name -> google.protobuf.Timestamp
	4, // 1: api.v2.ColloRateWebStreamRequest.until:type_name -> google.protobuf.Timestamp
	2, // 2: api.v2.ColloRateWebStreamResponse.nodes:type_name -> api.v2.RateNode
	3, // 3: api.v2.ColloRateWebStreamResponse.edges:type_name -> api.v2.RateEdge
	0, // 4: api.v2.ColloRateWebService.ColloRateWebStream:input_type -> api.v2.ColloRateWebStreamRequest
	1, // 5: api.v2.ColloRateWebService.ColloRateWebStream:output_type -> api.v2.ColloRateWebStreamResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v2_collo_proto_init() }
func file_api_v2_collo_proto_init() {
	if File_api_v2_collo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v2_collo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColloRateWebStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v2_collo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColloRateWebStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v2_collo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v2_collo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateEdge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v2_collo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v2_collo_proto_goTypes,
		DependencyIndexes: file_api_v2_collo_proto_depIdxs,
		MessageInfos:      file_api_v2_collo_proto_msgTypes,
	}.Build()
	File_api_v2_collo_proto = out.File
	file_api_v2_collo_proto_rawDesc = nil
	file_api_v2_collo_proto_goTypes = nil
	file_api_v2_collo_proto_depIdxs = nil
}
