version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - '*'
  - package-ecosystem: 'npm'
    directory: '/web'
    schedule:
      interval: 'monthly'
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - '*'
