// @generated by protoc-gen-connect-es v1.2.0 with parameter "target=ts"
// @generated from file api/v3/collo.proto (package api.v3, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { NetworkStreamRequest, NetworkStreamResponse, NodeRateStreamRequest, NodeRateStreamResponse } from "./collo_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v3.MintGreenService
 */
export const MintGreenService = {
  typeName: "api.v3.MintGreenService",
  methods: {
    /**
     * @generated from rpc api.v3.MintGreenService.NetworkStream
     */
    networkStream: {
      name: "NetworkStream",
      I: NetworkStreamRequest,
      O: NetworkStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc api.v3.MintGreenService.NodeRateStream
     */
    nodeRateStream: {
      name: "NodeRateStream",
      I: NodeRateStreamRequest,
      O: NodeRateStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

