// @generated by protoc-gen-es v1.6.0 with parameter "target=js"
// @generated from file api/v2/collo.proto (package api.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message api.v2.ColloRateWebStreamRequest
 */
export const ColloRateWebStreamRequest = proto3.makeMessageType(
  "api.v2.ColloRateWebStreamRequest",
  () => [
    { no: 1, name: "keyword", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "from", kind: "message", T: Timestamp },
    { no: 3, name: "until", kind: "message", T: Timestamp },
    { no: 4, name: "forcus_node_id", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 5, name: "part_of_speech_types", kind: "scalar", T: 13 /* ScalarType.UINT32 */, repeated: true },
    { no: 6, name: "stopwords", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 7, name: "mode", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 8, name: "forcus_group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message api.v2.ColloRateWebStreamResponse
 */
export const ColloRateWebStreamResponse = proto3.makeMessageType(
  "api.v2.ColloRateWebStreamResponse",
  () => [
    { no: 1, name: "nodes", kind: "message", T: RateNode, repeated: true },
    { no: 2, name: "edges", kind: "message", T: RateEdge, repeated: true },
    { no: 3, name: "dones", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "needs", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 5, name: "meta", kind: "message", T: Meta },
  ],
);

/**
 * @generated from message api.v2.RateNode
 */
export const RateNode = proto3.makeMessageType(
  "api.v2.RateNode",
  () => [
    { no: 1, name: "node_id", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "word", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "rate", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ],
);

/**
 * @generated from message api.v2.RateEdge
 */
export const RateEdge = proto3.makeMessageType(
  "api.v2.RateEdge",
  () => [
    { no: 1, name: "edge_id", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "node_id1", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "node_id2", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "rate", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ],
);

/**
 * @generated from message api.v2.Meta
 */
export const Meta = proto3.makeMessageType(
  "api.v2.Meta",
  () => [
    { no: 1, name: "group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "from", kind: "message", T: Timestamp },
    { no: 3, name: "until", kind: "message", T: Timestamp },
    { no: 4, name: "metas", kind: "message", T: DocMeta, repeated: true },
  ],
);

/**
 * @generated from message api.v2.DocMeta
 */
export const DocMeta = proto3.makeMessageType(
  "api.v2.DocMeta",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "group_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "at", kind: "message", T: Timestamp },
    { no: 5, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

