// @generated by protoc-gen-es v1.6.0 with parameter "target=js"
// @generated from file api/v2/collo.proto (package api.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message api.v2.ColloNetworkStreamRequest
 */
export const ColloNetworkStreamRequest = proto3.makeMessageType(
  "api.v2.ColloNetworkStreamRequest",
  () => [
    { no: 1, name: "keyword", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "from", kind: "message", T: Timestamp },
    { no: 3, name: "until", kind: "message", T: Timestamp },
    { no: 4, name: "forcus_node_id", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * @generated from message api.v2.ColloNetworkStreamResponse
 */
export const ColloNetworkStreamResponse = proto3.makeMessageType(
  "api.v2.ColloNetworkStreamResponse",
  () => [
    { no: 1, name: "nodes", kind: "message", T: Node, repeated: true },
    { no: 2, name: "edges", kind: "message", T: Edge, repeated: true },
    { no: 3, name: "dones", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "needs", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * @generated from message api.v2.ColloWebStreamRequest
 */
export const ColloWebStreamRequest = proto3.makeMessageType(
  "api.v2.ColloWebStreamRequest",
  () => [
    { no: 1, name: "keyword", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "from", kind: "message", T: Timestamp },
    { no: 3, name: "until", kind: "message", T: Timestamp },
    { no: 4, name: "forcus_node_id", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * @generated from message api.v2.ColloWebStreamResponse
 */
export const ColloWebStreamResponse = proto3.makeMessageType(
  "api.v2.ColloWebStreamResponse",
  () => [
    { no: 1, name: "nodes", kind: "message", T: Node, repeated: true },
    { no: 2, name: "edges", kind: "message", T: Edge, repeated: true },
    { no: 3, name: "dones", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "needs", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * @generated from message api.v2.Node
 */
export const Node = proto3.makeMessageType(
  "api.v2.Node",
  () => [
    { no: 1, name: "node_id", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "word", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message api.v2.Edge
 */
export const Edge = proto3.makeMessageType(
  "api.v2.Edge",
  () => [
    { no: 1, name: "edge_id", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "node_id1", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "node_id2", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "count", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

