// @generated by protoc-gen-connect-es v1.2.0 with parameter "target=ts"
// @generated from file api/v2/collo.proto (package api.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ColloRateWebStreamRequest, ColloRateWebStreamResponse } from "./collo_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service api.v2.ColloRateWebService
 */
export const ColloRateWebService = {
  typeName: "api.v2.ColloRateWebService",
  methods: {
    /**
     * @generated from rpc api.v2.ColloRateWebService.ColloRateWebStream
     */
    colloRateWebStream: {
      name: "ColloRateWebStream",
      I: ColloRateWebStreamRequest,
      O: ColloRateWebStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

