version: '3'

services:
  collo-api:
    build:
      context: ../
      dockerfile: ./.docker/dockerfile.local
    container_name: "collo-api"
    ports:
      - "8088:8080"
    volumes:
      - ../:/workspaces/go:cached
    environment:
      - APP_PORT=8080
      - ENV=local
      - CERT_PATH=/workspaces/go/ssl/localhost.pem
      - KEY_PATH=/workspaces/go/ssl/localhost-key.pem
      - CLIENT_HOST=http://localhost:3033
      - CGO_LDFLAGS="-L/usr/local/lib -lmecab -lstdc++"
      - CGO_CFLAGS="-I/path/to/include"
    tty: true
    networks:
      - collo-network
    
networks:
  collo-network:
    name: collo-network