version: '3'

services:
  collo-api:
    build:
      context: ../
      dockerfile: ./.docker/dockerfile.local
    container_name: "collo-api"
    ports:
      - "8088:8080"
    volumes:
      - ../:/workspaces/go:cached
    environment:
      - APP_PORT=8080
    tty: true